# Phase 04 — Dataset Collection & Sourcing
## CodeMentor-LLM
Loading and exploring datasets for fine-tuning
meta-llama/Meta-Llama-3-8B-Instruct on coding Q&A task.

## Datasets
- Primary: sahil2801/CodeAlpaca-20k
- Backup: iamtarun/python_code_instructions_18k_alpaca

# Libraries

In [1]:
!pip install -q datasets==3.3.2 pandas==2.2.3

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.7/12.7 MB 59.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 9.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 2.2.3 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.

# Load primary dataset

In [3]:
from datasets import load_dataset

# Load primary dataset
print("Loading primary dataset...")
primary_dataset = load_dataset("sahil2801/CodeAlpaca-20k")
print(primary_dataset)

Loading primary dataset...
DatasetDict({
    train: Dataset({
        features: ['output', 'instruction', 'input'],
        num_rows: 20022
    })
})

# Login with HF token

In [4]:
from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF_TOKEN')
login(token=hf_token)
print("Logged in successfully")

Logged in successfully

# Explore primary dataset

In [5]:
import pandas as pd

# Convert to dataframe
df_primary = pd.DataFrame(primary_dataset["train"])

# Basic info
print(f"Dataset size: {len(df_primary)}")
print(f"Columns: {df_primary.columns.tolist()}")
print(f"\nFirst 3 rows:")
df_primary.head(3)

Dataset size: 20022
Columns: ['output', 'instruction', 'input']

First 3 rows:

,output,instruction,input
0,"arr = [2, 4, 6, 8, 10]",Create an array of length 5 which contains all...,
1,Height of triangle = opposite side length * si...,Formulate an equation to calculate the height ...,
2,"def replace(self, replace_with):\n new_stri...",Write a replace method for a string class whic...,"string = ""Hello World!""\nreplace_with = ""Greet..."

#  Preview single sample

In [6]:
# Preview first sample in detail
sample = primary_dataset["train"][0]
print("INSTRUCTION:", sample["instruction"])
print("\nINPUT:", sample["input"])
print("\nOUTPUT:", sample["output"])

INSTRUCTION: Create an array of length 5 which contains all even numbers between 1 and 10.

INPUT:

OUTPUT: arr = [2, 4, 6, 8, 10]

# Load backup dataset

In [7]:
# Load backup dataset
print("Loading backup dataset...")
backup_dataset = load_dataset("iamtarun/python_code_instructions_18k_alpaca")
print(backup_dataset)

Loading backup dataset...

README.md:   0%|          | 0.00/905 [00:00<?, ?B/s]

data/train-00000-of-00001-8b6e212f3e1ece(…):   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/18612 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['instruction', 'input', 'output', 'prompt'],
        num_rows: 18612
    })
})

# Explore backup dataset

In [8]:
# Convert to dataframe
df_backup = pd.DataFrame(backup_dataset["train"])

# Basic info
print(f"Dataset size: {len(df_backup)}")
print(f"Columns: {df_backup.columns.tolist()}")
print(f"\nFirst 3 rows:")
df_backup.head(3)

Dataset size: 18612
Columns: ['instruction', 'input', 'output', 'prompt']

First 3 rows:

,instruction,input,output,prompt
0,Create a function to calculate the sum of a se...,"[1, 2, 3, 4, 5]",# Python code\ndef sum_sequence(sequence):\n ...,Below is an instruction that describes a task....
1,Generate a Python code for crawling a website ...,website: www.example.com \ndata to crawl: phon...,import requests\nimport re\n\ndef crawl_websit...,Below is an instruction that describes a task....
2,Create a Python list comprehension to get the ...,,"[x*x for x in [1, 2, 3, 5, 8, 13]]",Below is an instruction that describes a task....

# Compare both datasets

In [9]:
# Compare both datasets
print("=" * 50)
print("DATASET COMPARISON")
print("=" * 50)
print(f"\nPrimary — CodeAlpaca-20K:")
print(f"  Samples : {len(df_primary)}")
print(f"  Columns : {df_primary.columns.tolist()}")
print(f"  Source  : sahil2801/CodeAlpaca-20k")
print(f"  License : Apache 2.0")

print(f"\nBackup — Python Code Instructions 18K:")
print(f"  Samples : {len(df_backup)}")
print(f"  Columns : {df_backup.columns.tolist()}")
print(f"  Source  : iamtarun/python_code_instructions_18k_alpaca")
print(f"  License : Apache 2.0")

print(f"\nTotal combined samples: {len(df_primary) + len(df_backup)}")

==================================================
DATASET COMPARISON
==================================================

Primary — CodeAlpaca-20K:
  Samples : 20022
  Columns : ['output', 'instruction', 'input']
  Source  : sahil2801/CodeAlpaca-20k
  License : Apache 2.0

Backup — Python Code Instructions 18K:
  Samples : 18612
  Columns : ['instruction', 'input', 'output', 'prompt']
  Source  : iamtarun/python_code_instructions_18k_alpaca
  License : Apache 2.0

Total combined samples: 38634

# Save to HuggingFace Hub

In [10]:
from datasets import DatasetDict

# Push primary dataset to HF Hub
print("Pushing primary dataset to HF Hub...")
primary_dataset.push_to_hub("Abdulmoiz123/codementor-llm-raw-primary")
print("Primary dataset pushed successfully")

# Push backup dataset to HF Hub
print("\nPushing backup dataset to HF Hub...")
backup_dataset.push_to_hub("Abdulmoiz123/codementor-llm-raw-backup")
print("Backup dataset pushed successfully")

Pushing primary dataset to HF Hub...

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/21 [00:00<?, ?ba/s]

Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.
WARNING:huggingface_hub._commit_api:Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.

Primary dataset pushed successfully

Pushing backup dataset to HF Hub...

Uploading the dataset shards:   0%|          | 0/1 [00:00<?, ?it/s]

Creating parquet from Arrow format:   0%|          | 0/19 [00:00<?, ?ba/s]

Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.
WARNING:huggingface_hub._commit_api:Uploading files as a binary IO buffer is not supported by Xet Storage. Falling back to HTTP upload.

Backup dataset pushed successfully